# Generated by Django 5.0.6 on 2026-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gold_price_usd_troy', models.DecimalField(decimal_places=4, help_text='Gold spot price per troy oz (31.1035g) in USD.', max_digits=14)),
                ('gold_price_usd_gram', models.DecimalField(decimal_places=4, help_text='Gold spot price per gram in USD.', max_digits=14)),
                ('gold_prev_close_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Gold previous close price in USD.', max_digits=14, null=True)),
                ('gold_change_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Gold price change from previous close (USD).', max_digits=12, null=True)),
                ('gold_change_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Gold price percentage change from previous close.', max_digits=8, null=True)),
                ('silver_price_usd_troy', models.DecimalField(blank=True, decimal_places=4, help_text='Silver spot price per troy oz in USD.', max_digits=14, null=True)),
                ('silver_price_usd_gram', models.DecimalField(blank=True, decimal_places=4, help_text='Silver spot price per gram in USD.', max_digits=14, null=True)),
                ('usd_myr_rate', models.DecimalField(blank=True, decimal_places=4, help_text='USD to MYR exchange rate at fetch time.', max_digits=10, null=True)),
                ('nisab_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Nisab in USD = gold_price_per_gram_usd × 85g.', max_digits=14, null=True)),
                ('nisab_myr', models.DecimalField(blank=True, decimal_places=4, help_text='Nisab in MYR = nisab_usd × usd_myr_rate.', max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Gold Price',
                'verbose_name_plural': 'Gold Prices',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
