# Generated by Django 6.0.6 on 2026-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetalSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], max_length=10, unique=True)),
                ('spot_price_per_ounce', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.FloatField(default=0)),
                ('as_of', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
