"""
News app — caches headlines from NewsAPI.
AI-generated summaries are stored alongside each article.
"""

from django.db import models


class NewsArticle(models.Model):
    """
    A single news article fetched from NewsAPI.
    Ticker tags allow filtering by symbol (e.g., AAPL, MACRO, KLSE).
    """
    headline = models.TextField()
    description = models.TextField(blank=True)
    source = models.CharField(max_length=200, blank=True)
    author = models.CharField(max_length=200, blank=True)
    url = models.URLField(max_length=1000, unique=True)
    image_url = models.URLField(max_length=1000, blank=True)
    published_at = models.DateTimeField(db_index=True)

    # Tags for filtering (stored as JSON array of strings)
    # e.g., ["AAPL", "NVDA"] or ["MACRO"] or ["KLSE", "BURSA"]
    ticker_tags = models.JSONField(default=list, blank=True)

    # Category for display badge: MACRO, TICKER, SECTOR
    category = models.CharField(max_length=50, default="MACRO")

    # LM Studio AI summary (populated on demand)
    summary_ai = models.TextField(
        blank=True,
        help_text="3-bullet AI summary generated by local LM Studio model."
    )
    summary_generated_at = models.DateTimeField(null=True, blank=True)

    fetched_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-published_at"]
        verbose_name = "News Article"
        verbose_name_plural = "News Articles"
        indexes = [
            models.Index(fields=["-published_at"]),
        ]

    def __str__(self):
        return f"[{self.source}] {self.headline[:60]}"
