# Generated by Django 5.0.6 on 2026-06-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('MYR', 'Malaysian Ringgit (MYR)'), ('USD', 'US Dollar (USD)')], default='MYR', max_length=3)),
                ('gold_price_per_gram', models.DecimalField(decimal_places=4, help_text='Live gold price per gram in the selected currency.', max_digits=14)),
                ('gold_price_per_troy_oz', models.DecimalField(decimal_places=4, help_text='Live gold price per troy oz (31.1035g) in the selected currency.', max_digits=14)),
                ('nisab_grams', models.DecimalField(decimal_places=2, default=85.0, help_text='Nisab threshold in grams of gold (AAOIFI: 85g).', max_digits=8)),
                ('nisab_value', models.DecimalField(decimal_places=4, help_text='Nisab monetary value = nisab_grams × gold_price_per_gram.', max_digits=18)),
                ('usd_myr_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate used for currency conversion.', max_digits=10, null=True)),
                ('portfolio_value', models.DecimalField(decimal_places=4, help_text='Total portfolio market value at calculation time.', max_digits=18)),
                ('is_above_nisab', models.BooleanField(help_text='True if portfolio_value >= nisab_value.')),
                ('zakat_rate', models.DecimalField(decimal_places=4, default=0.025, help_text='Zakat rate (standard 2.5%).', max_digits=6)),
                ('zakat_due', models.DecimalField(decimal_places=4, help_text='Zakat due = portfolio_value × zakat_rate (if above nisab).', max_digits=18)),
            ],
            options={
                'verbose_name': 'Zakat Record',
                'verbose_name_plural': 'Zakat Records',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Number of shares/units held.', max_digits=18)),
                ('avg_cost', models.DecimalField(decimal_places=4, help_text="Average cost per share in the ticker's native currency.", max_digits=18)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='market.ticker')),
            ],
            options={
                'verbose_name': 'Holding',
                'verbose_name_plural': 'Holdings',
                'ordering': ['ticker__symbol', 'purchase_date'],
            },
        ),
    ]
