# Generated by Django 6.0.6 on 2026-07-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('zakat_assessment_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.quote')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfolioaccount')),
            ],
        ),
    ]
