# Generated by Django 6.0.6 on 2026-07-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShariahAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-compliant'), ('questionable', 'Questionable')], max_length=20)),
                ('debt_to_market_cap', models.FloatField(default=0)),
                ('interest_income_ratio', models.FloatField(default=0)),
                ('non_compliant_income_ratio', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='market.quote')),
            ],
        ),
    ]
