# Generated by Django 5.0.6 on 2026-06-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shariah_status', models.CharField(blank=True, max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('market_cap_category', models.CharField(blank=True, help_text='mega/large/mid/small/micro — computed from market_cap.', max_length=20)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pct_change', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screener_cache', to='market.ticker')),
            ],
            options={
                'verbose_name': 'Screener Cache',
                'verbose_name_plural': 'Screener Caches',
                'ordering': ['-market_cap'],
            },
        ),
        migrations.CreateModel(
            name='ShariahAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('DOUBTFUL', 'Doubtful'), ('PENDING', 'Pending Review')], default='PENDING', max_length=20)),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=5, help_text='(total_debt + cash) / total_assets. Threshold: < 33%', max_digits=8, null=True)),
                ('debt_ratio_pass', models.BooleanField(blank=True, null=True)),
                ('revenue_ratio', models.DecimalField(blank=True, decimal_places=5, help_text='interest_income / total_revenue. Threshold: < 5%', max_digits=8, null=True)),
                ('revenue_ratio_pass', models.BooleanField(blank=True, null=True)),
                ('receivables_ratio', models.DecimalField(blank=True, decimal_places=5, help_text='accounts_receivable / total_assets. Threshold: < 70%', max_digits=8, null=True)),
                ('receivables_ratio_pass', models.BooleanField(blank=True, null=True)),
                ('business_activity_ok', models.BooleanField(default=True, help_text='False if core business is haram (alcohol, gambling, riba, etc.)')),
                ('excluded_sector', models.BooleanField(default=False, help_text='True if sector is on the hard-excluded list (auto-fail).')),
                ('aaoifi_pass', models.BooleanField(blank=True, help_text='AAOIFI global Shariah standard (used by GCC, Malaysia, globally).', null=True)),
                ('sc_malaysia_pass', models.BooleanField(blank=True, help_text='Securities Commission Malaysia Shariah Advisory Council standard.', null=True)),
                ('data_fiscal_year', models.IntegerField(blank=True, null=True)),
                ('audit_notes', models.TextField(blank=True, help_text='Human-readable audit summary including qualitative findings.')),
                ('purification_rate', models.DecimalField(blank=True, decimal_places=5, help_text='Fraction of each dividend to purify (donate). Equals revenue_ratio.', max_digits=8, null=True)),
                ('screened_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shariah_audit', to='market.ticker')),
            ],
            options={
                'verbose_name': 'Shariah Audit',
                'verbose_name_plural': 'Shariah Audits',
            },
        ),
    ]
