# Generated by Django 6.0.6 on 2026-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shariah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shariahassessment',
            name='liquid_assets_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shariahassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
