# Generated by Django 5.0.6 on 2026-06-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('is_etf', models.BooleanField(default=False)),
                ('is_bursa', models.BooleanField(default=False)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pct_change', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('day_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticker',
                'verbose_name_plural': 'Tickers',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=18)),
                ('high', models.DecimalField(decimal_places=4, max_digits=18)),
                ('low', models.DecimalField(decimal_places=4, max_digits=18)),
                ('close', models.DecimalField(decimal_places=4, max_digits=18)),
                ('volume', models.BigIntegerField()),
                ('adj_close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.ticker')),
            ],
            options={
                'verbose_name': 'Price History',
                'ordering': ['-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='Default', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='market.ticker')),
            ],
            options={
                'ordering': ['list_name', 'sort_order', 'ticker__symbol'],
                'unique_together': {('ticker', 'list_name')},
            },
        ),
    ]
