# Generated by Django 5.0.6 on 2026-06-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=10)),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_quarter', models.IntegerField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('cash_and_equivalents', models.BigIntegerField(blank=True, null=True)),
                ('short_term_investments', models.BigIntegerField(blank=True, null=True)),
                ('accounts_receivable', models.BigIntegerField(blank=True, null=True)),
                ('inventory', models.BigIntegerField(blank=True, null=True)),
                ('total_current_assets', models.BigIntegerField(blank=True, null=True)),
                ('net_ppe', models.BigIntegerField(blank=True, null=True)),
                ('goodwill', models.BigIntegerField(blank=True, null=True)),
                ('intangible_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_non_current_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('accounts_payable', models.BigIntegerField(blank=True, null=True)),
                ('short_term_debt', models.BigIntegerField(blank=True, null=True)),
                ('total_current_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('long_term_debt', models.BigIntegerField(blank=True, null=True)),
                ('total_non_current_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('total_debt', models.BigIntegerField(blank=True, null=True)),
                ('total_equity', models.BigIntegerField(blank=True, null=True)),
                ('retained_earnings', models.BigIntegerField(blank=True, null=True)),
                ('common_stock', models.BigIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='market.ticker')),
            ],
            options={
                'verbose_name': 'Balance Sheet',
                'ordering': ['-fiscal_year', '-fiscal_quarter'],
                'unique_together': {('ticker', 'period', 'fiscal_year', 'fiscal_quarter')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=10)),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_quarter', models.IntegerField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('depreciation_amortization', models.BigIntegerField(blank=True, null=True)),
                ('stock_based_compensation', models.BigIntegerField(blank=True, null=True)),
                ('changes_in_working_capital', models.BigIntegerField(blank=True, null=True)),
                ('operating_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('capex', models.BigIntegerField(blank=True, null=True)),
                ('acquisitions', models.BigIntegerField(blank=True, null=True)),
                ('investing_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('debt_repayment', models.BigIntegerField(blank=True, null=True)),
                ('dividends_paid', models.BigIntegerField(blank=True, null=True)),
                ('share_buybacks', models.BigIntegerField(blank=True, null=True)),
                ('financing_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('free_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('net_change_in_cash', models.BigIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='market.ticker')),
            ],
            options={
                'verbose_name': 'Cash Flow Statement',
                'ordering': ['-fiscal_year', '-fiscal_quarter'],
                'unique_together': {('ticker', 'period', 'fiscal_year', 'fiscal_quarter')},
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=10)),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_quarter', models.IntegerField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('cost_of_revenue', models.BigIntegerField(blank=True, null=True)),
                ('gross_profit', models.BigIntegerField(blank=True, null=True)),
                ('gross_profit_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('operating_expenses', models.BigIntegerField(blank=True, null=True)),
                ('operating_income', models.BigIntegerField(blank=True, null=True)),
                ('operating_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('ebitda', models.BigIntegerField(blank=True, null=True)),
                ('interest_expense', models.BigIntegerField(blank=True, null=True)),
                ('interest_income', models.BigIntegerField(blank=True, null=True)),
                ('pretax_income', models.BigIntegerField(blank=True, null=True)),
                ('income_tax_expense', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('net_profit_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('eps_diluted', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('weighted_avg_shares', models.BigIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_statements', to='market.ticker')),
            ],
            options={
                'verbose_name': 'Income Statement',
                'ordering': ['-fiscal_year', '-fiscal_quarter'],
                'unique_together': {('ticker', 'period', 'fiscal_year', 'fiscal_quarter')},
            },
        ),
    ]
