# Generated by Django 6.0.6 on 2026-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('source', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True, default='')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('related_symbols', models.CharField(blank=True, default='', max_length=120)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
