# Generated by Django 5.0.6 on 2026-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('ticker_tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(default='MACRO', max_length=50)),
                ('summary_ai', models.TextField(blank=True, help_text='3-bullet AI summary generated by local LM Studio model.')),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_newsar_publish_db2481_idx')],
            },
        ),
    ]
